# Generated by Django 4.1.4 on 2023-02-12 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("client", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
