# Generated by Django 4.1.4 on 2023-02-09 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('capacity', models.IntegerField()),
                ('bookseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.bookseller')),
            ],
        ),
    ]
